// <auto-generated />
using System;
using Erp.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erp.Server.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260724173001_AddDelhiveryWarehouses")]
    partial class AddDelhiveryWarehouses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Erp.Server.Models.Address", b =>
                {
                    b.Property<int>("ad_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ad_id"));

                    b.Property<string>("ad_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ad_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("ad_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ad_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ad_is_default_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ad_pincode")
                        .HasColumnType("int");

                    b.HasKey("ad_id");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("Erp.Server.Models.Barcode", b =>
                {
                    b.Property<int>("b_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("b_id"));

                    b.Property<string>("b_bar_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("b_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("b_cre_by_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("b_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("b_prod_id")
                        .HasColumnType("int");

                    b.HasKey("b_id");

                    b.ToTable("Barcodes");
                });

            modelBuilder.Entity("Erp.Server.Models.Blog", b =>
                {
                    b.Property<int>("b_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("b_id"));

                    b.Property<string>("b_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("b_content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("b_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("b_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("b_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("b_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("b_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("b_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("b_id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Erp.Server.Models.Cart", b =>
                {
                    b.Property<int>("c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("c_id"));

                    b.Property<int?>("c_color")
                        .HasColumnType("int");

                    b.Property<string>("c_color_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("c_country")
                        .HasColumnType("int");

                    b.Property<int?>("c_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("c_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("c_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("c_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("c_product")
                        .HasColumnType("int");

                    b.Property<int?>("c_qty")
                        .HasColumnType("int");

                    b.Property<int?>("c_size")
                        .HasColumnType("int");

                    b.Property<string>("c_size_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_attachements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_category")
                        .HasColumnType("int");

                    b.Property<string>("p_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_division")
                        .HasColumnType("int");

                    b.Property<string>("p_division_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_id")
                        .HasColumnType("int");

                    b.Property<string>("p_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("p_overall_rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("p_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("p_short_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_sub_category")
                        .HasColumnType("int");

                    b.Property<string>("p_sub_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_sub_division")
                        .HasColumnType("int");

                    b.Property<string>("p_sub_division_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("c_id");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("Erp.Server.Models.Category", b =>
                {
                    b.Property<int>("ct_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ct_id"));

                    b.Property<string>("ct_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ct_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("ct_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ct_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ct_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ct_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ct_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Erp.Server.Models.ConstantValue", b =>
                {
                    b.Property<int>("cv_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cv_id"));

                    b.Property<string>("cv_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cv_cre_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("cv_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("cv_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cv_value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cv_id");

                    b.ToTable("ConstantValues");
                });

            modelBuilder.Entity("Erp.Server.Models.Customer", b =>
                {
                    b.Property<int>("c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("c_id"));

                    b.Property<string>("c_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_agree_terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("c_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("c_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("c_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("c_date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("c_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_is_get_updates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("c_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Erp.Server.Models.CustomerOrder", b =>
                {
                    b.Property<int>("co_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("co_id"));

                    b.Property<decimal?>("co_amount")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int?>("co_c_address")
                        .HasColumnType("int");

                    b.Property<string>("co_c_address_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("co_color")
                        .HasColumnType("int");

                    b.Property<string>("co_color_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("co_completed_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("co_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("co_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("co_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("co_customer")
                        .HasColumnType("int");

                    b.Property<string>("co_customer_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("co_customer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("co_customer_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("co_delivery_charge")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("co_discount_amount")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("co_discount_perc")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("co_gst_amount")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("co_gst_perc")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("co_is_canceled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("co_is_returned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("co_net_amount")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("co_payment_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("co_product")
                        .HasColumnType("int");

                    b.Property<string>("co_product_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("co_promo_code")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("co_qty")
                        .HasColumnType("int");

                    b.Property<string>("co_refund_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("co_return_id")
                        .HasColumnType("int");

                    b.Property<int?>("co_size")
                        .HasColumnType("int");

                    b.Property<string>("co_size_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("co_status")
                        .HasColumnType("int");

                    b.Property<string>("co_status_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("co_unit_price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("co_waybill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_attachements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_category")
                        .HasColumnType("int");

                    b.Property<string>("p_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_division")
                        .HasColumnType("int");

                    b.Property<string>("p_division_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_id")
                        .HasColumnType("int");

                    b.Property<string>("p_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("p_overall_rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("p_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("p_short_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_sub_category")
                        .HasColumnType("int");

                    b.Property<string>("p_sub_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_sub_division")
                        .HasColumnType("int");

                    b.Property<string>("p_sub_division_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("co_id");

                    b.ToTable("CustomerOrders");
                });

            modelBuilder.Entity("Erp.Server.Models.DashboardStats", b =>
                {
                    b.Property<int>("ActiveCustomers")
                        .HasColumnType("int");

                    b.Property<int>("ActiveProducts")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyOrders")
                        .HasColumnType("int");

                    b.Property<int>("NewCustomersWeek")
                        .HasColumnType("int");

                    b.Property<int>("PendingShipments")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("DashboardStats");
                });

            modelBuilder.Entity("Erp.Server.Models.DbResult", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DbResult");
                });

            modelBuilder.Entity("Erp.Server.Models.DelhiveryWarehouse", b =>
                {
                    b.Property<int>("dw_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dw_id"));

                    b.Property<string>("dw_address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("dw_city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("dw_country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("dw_created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("dw_email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("dw_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("dw_phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("dw_pincode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("dw_registered_yn")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("dw_state")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("dw_id");

                    b.ToTable("DelhiveryWarehouses", (string)null);
                });

            modelBuilder.Entity("Erp.Server.Models.Expense", b =>
                {
                    b.Property<int>("e_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("e_id"));

                    b.Property<decimal?>("e_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("e_category")
                        .HasColumnType("int");

                    b.Property<string>("e_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("e_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("e_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("e_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("e_expense_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("e_payment_method")
                        .HasColumnType("int");

                    b.Property<string>("e_payment_method_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("e_id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Erp.Server.Models.Favourite", b =>
                {
                    b.Property<int>("f_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_id"));

                    b.Property<int?>("f_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("f_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("f_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("f_product")
                        .HasColumnType("int");

                    b.Property<string>("p_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_attachements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_category")
                        .HasColumnType("int");

                    b.Property<string>("p_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_division")
                        .HasColumnType("int");

                    b.Property<string>("p_division_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_id")
                        .HasColumnType("int");

                    b.Property<string>("p_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("p_overall_rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("p_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("p_short_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_sub_category")
                        .HasColumnType("int");

                    b.Property<string>("p_sub_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_sub_division")
                        .HasColumnType("int");

                    b.Property<string>("p_sub_division_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("f_id");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("Erp.Server.Models.Feedback", b =>
                {
                    b.Property<int>("f_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_id"));

                    b.Property<int>("f_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("f_cre_by_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("f_created_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("f_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("f_id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Erp.Server.Models.Income", b =>
                {
                    b.Property<int>("i_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("i_id"));

                    b.Property<decimal?>("i_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("i_category")
                        .HasColumnType("int");

                    b.Property<string>("i_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("i_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("i_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("i_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("i_income_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("i_payment_method")
                        .HasColumnType("int");

                    b.Property<string>("i_payment_method_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("i_remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("i_id");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("Erp.Server.Models.MasterData", b =>
                {
                    b.Property<int>("md_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("md_id"));

                    b.Property<string>("md_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("md_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("md_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("md_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("md_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("md_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("md_id");

                    b.ToTable("MasterDatas");
                });

            modelBuilder.Entity("Erp.Server.Models.MasterType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MasterTypes");
                });

            modelBuilder.Entity("Erp.Server.Models.Menu", b =>
                {
                    b.Property<int>("m_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("m_id"));

                    b.Property<int?>("m_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("m_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("m_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("m_fa_icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("m_link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("m_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("m_parrent")
                        .HasColumnType("int");

                    b.Property<string>("m_parrent_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("m_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("m_id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Erp.Server.Models.MenuType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("menuType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MenuTypes");
                });

            modelBuilder.Entity("Erp.Server.Models.OrderMovementHistory", b =>
                {
                    b.Property<int>("omh_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("omh_id"));

                    b.Property<int?>("omh_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("omh_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("omh_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("omh_order_no")
                        .HasColumnType("int");

                    b.Property<int?>("omh_status")
                        .HasColumnType("int");

                    b.Property<string>("omh_status_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("omh_workflow_id")
                        .HasColumnType("int");

                    b.HasKey("omh_id");

                    b.ToTable("OrderMovementHistories");
                });

            modelBuilder.Entity("Erp.Server.Models.PackagingType", b =>
                {
                    b.Property<int>("pt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pt_id"));

                    b.Property<string>("pt_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pt_breadth")
                        .HasColumnType("int");

                    b.Property<int?>("pt_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("pt_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("pt_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("pt_height")
                        .HasColumnType("int");

                    b.Property<int>("pt_length")
                        .HasColumnType("int");

                    b.Property<string>("pt_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pt_pkg_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pt_id");

                    b.ToTable("PackagingTypes");
                });

            modelBuilder.Entity("Erp.Server.Models.ProdAttachment", b =>
                {
                    b.Property<int>("pa_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pa_id"));

                    b.Property<int?>("pa_color")
                        .HasColumnType("int");

                    b.Property<string>("pa_color_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pa_cre_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("pa_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("pa_image_path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pa_prod_id")
                        .HasColumnType("int");

                    b.HasKey("pa_id");

                    b.ToTable("ProdAttachments");
                });

            modelBuilder.Entity("Erp.Server.Models.ProdColor", b =>
                {
                    b.Property<int>("pc_color")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pc_color"));

                    b.Property<string>("pc_color_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pc_color");

                    b.ToTable("ProdColors");
                });

            modelBuilder.Entity("Erp.Server.Models.ProdSize", b =>
                {
                    b.Property<int>("ps_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ps_id"));

                    b.Property<string>("ps_active_yn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ps_cre_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("ps_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ps_prod_id")
                        .HasColumnType("int");

                    b.Property<int>("ps_size")
                        .HasColumnType("int");

                    b.Property<string>("ps_size_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ps_id");

                    b.ToTable("ProdSizes");
                });

            modelBuilder.Entity("Erp.Server.Models.Product", b =>
                {
                    b.Property<int>("p_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("p_id"));

                    b.Property<string>("p_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_attachements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_category")
                        .HasColumnType("int");

                    b.Property<string>("p_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("p_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("p_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("p_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("p_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_division")
                        .HasColumnType("int");

                    b.Property<string>("p_division_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("p_overall_rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("p_packaging_type")
                        .HasColumnType("int");

                    b.Property<string>("p_packaging_type_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("p_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("p_short_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_sub_category")
                        .HasColumnType("int");

                    b.Property<string>("p_sub_category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("p_sub_division")
                        .HasColumnType("int");

                    b.Property<string>("p_sub_division_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("p_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Erp.Server.Models.ProductReview", b =>
                {
                    b.Property<int>("pr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pr_id"));

                    b.Property<int>("pr_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("pr_cre_by_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("pr_created_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("pr_head_line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pr_overall_rating")
                        .HasColumnType("int");

                    b.Property<int>("pr_prod_id")
                        .HasColumnType("int");

                    b.Property<string>("pr_review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pr_id");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("Erp.Server.Models.Promocode", b =>
                {
                    b.Property<int>("pc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pc_id"));

                    b.Property<string>("pc_active_yn")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("pc_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("pc_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("pc_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("pc_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("pc_discount_perc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("pc_expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("pc_max_discount_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pc_min_order_amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("pc_id");

                    b.ToTable("Promocodes");
                });

            modelBuilder.Entity("Erp.Server.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("po_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("po_id"));

                    b.Property<int?>("po_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("po_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("po_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("po_harddisk")
                        .HasColumnType("int");

                    b.Property<int?>("po_make")
                        .HasColumnType("int");

                    b.Property<int?>("po_model")
                        .HasColumnType("int");

                    b.Property<int?>("po_processor")
                        .HasColumnType("int");

                    b.Property<int?>("po_ram")
                        .HasColumnType("int");

                    b.HasKey("po_id");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Erp.Server.Models.ReturnOrder", b =>
                {
                    b.Property<int>("ro_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ro_id"));

                    b.Property<string>("ro_comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ro_completed_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ro_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("ro_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ro_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ro_customer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ro_net_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ro_order_no")
                        .HasColumnType("int");

                    b.Property<string>("ro_payment_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ro_prod_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ro_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ro_status")
                        .HasColumnType("int");

                    b.Property<string>("ro_status_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ro_id");

                    b.ToTable("ReturnOrders");
                });

            modelBuilder.Entity("Erp.Server.Models.Role", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("r_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("r_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("r_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("r_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("r_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Erp.Server.Models.SellingPrice", b =>
                {
                    b.Property<int>("sp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sp_id"));

                    b.Property<int?>("sp_country_id")
                        .HasColumnType("int");

                    b.Property<string>("sp_country_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("sp_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("sp_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("sp_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("sp_end_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("sp_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("sp_price_type")
                        .HasColumnType("int");

                    b.Property<string>("sp_price_type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("sp_prod_id")
                        .HasColumnType("int");

                    b.Property<string>("sp_prod_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("sp_start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("sp_id");

                    b.ToTable("SellingPrices");
                });

            modelBuilder.Entity("Erp.Server.Models.Slider", b =>
                {
                    b.Property<int>("s_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("s_id"));

                    b.Property<string>("s_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("s_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("s_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("s_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("s_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("s_id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Erp.Server.Models.Status", b =>
                {
                    b.Property<int>("s_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("s_id"));

                    b.Property<int?>("cos_priority")
                        .HasColumnType("int");

                    b.Property<string>("s_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("s_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("s_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("s_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("s_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("s_workflow_id")
                        .HasColumnType("int");

                    b.HasKey("s_id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Erp.Server.Models.Supplier", b =>
                {
                    b.Property<int>("s_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("s_id"));

                    b.Property<string>("s_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("s_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("s_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("s_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("s_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("s_id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Erp.Server.Models.User", b =>
                {
                    b.Property<int>("u_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("u_id"));

                    b.Property<string>("u_active_yn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_agree_terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("u_cre_by")
                        .HasColumnType("int");

                    b.Property<string>("u_cre_by_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("u_cre_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("u_date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("u_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_email_verified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_is_admin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_is_get_updates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_phone_verified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("u_role_id")
                        .HasColumnType("int");

                    b.Property<string>("u_role_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("u_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Erp.Server.Models.Waybill", b =>
                {
                    b.Property<int>("wb_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("wb_id"));

                    b.Property<DateTime>("wb_created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("wb_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("wb_order_id")
                        .HasColumnType("int");

                    b.Property<string>("wb_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("wb_used_date")
                        .HasColumnType("datetime2");

                    b.HasKey("wb_id");

                    b.ToTable("Waybills", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
